/**
 * Auto-generated API implementations
 * This file is automatically generated based on your API dependencies.
 * Do not edit manually - changes will be overwritten.
 */

import { Agent } from '@greaseclaw/workflow-sdk';

/**
 * WorkflowApis interface - methods generated from your API dependencies
 */
export interface WorkflowApis {
  login: (username: string, password: string) => Promise<unknown>;
  check_login: () => Promise<unknown>;
  get_message: (goods_url: string) => Promise<unknown>;
  search: (querystring: string) => Promise<unknown>;
  inquire: (goods_url: string, message: string) => Promise<unknown>;
  payment: (goods_url: string) => Promise<unknown>;
}

/**
 * Creates API client using agent.call()
 */
export function createWorkflowApis(agent: Agent): WorkflowApis {
  return {
    /**
     * Login
     * Login
     * @endpoint /v1/custom/login
     */
    async login(username: string, password: string): Promise<unknown> {
      const { data } = await agent.call('/v1/custom/login', {
        method: 'POST',
        body: { username, password },
      });
      return data;
    },

    /**
     * Check Login
     * Check Login
     * @endpoint /v1/custom/check_login
     */
    async check_login(): Promise<unknown> {
      const { data } = await agent.call('/v1/custom/check_login', {
        method: 'POST',
      });
      return data;
    },

    /**
     * Get Message
     * Get Message
     * @endpoint /v1/custom/get_message
     */
    async get_message(goods_url: string): Promise<unknown> {
      const { data } = await agent.call('/v1/custom/get_message', {
        method: 'POST',
        body: { goods_url },
      });
      return data;
    },

    /**
     * Search
     * Search
     * @endpoint /v1/custom/search
     */
    async search(querystring: string): Promise<unknown> {
      const { data } = await agent.call('/v1/custom/search', {
        method: 'POST',
        body: { querystring },
      });
      return data;
    },

    /**
     * Inquire
     * Inquire
     * @endpoint /v1/custom/inquire
     */
    async inquire(goods_url: string, message: string): Promise<unknown> {
      const { data } = await agent.call('/v1/custom/inquire', {
        method: 'POST',
        body: { goods_url, message },
      });
      return data;
    },

    /**
     * Payment
     * Payment
     * @endpoint /v1/custom/payment
     */
    async payment(goods_url: string): Promise<unknown> {
      const { data } = await agent.call('/v1/custom/payment', {
        method: 'POST',
        body: { goods_url },
      });
      return data;
    },
  };
}